export const SET_PICK_UP_ADDRESS_INPUT = 'SET_PICK_UP_ADDRESS_INPUT';
export const SET_DROP_OFF_ADDRESS_INPUT = 'SET_DROP_OFF_ADDRESS_INPUT';
export const SET_TOAST_VISIBILITY = 'SET_TOAST_VISIBILITY';
export const SET_CREATING_JOB = 'SET_CREATING_JOB';
export const SET_PICK_UP_STATUS = 'SET_PICK_UP_STATUS';
export const SET_DROP_OFF_STATUS = 'SET_DROP_OFF_STATUS';
export const RESET_INPUTS = 'RESET_INPUTS';
